# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  Major: '0'
  Minor: '1'
  Patch: '0'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--no-restore'
    projects: src/**/*.csproj

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: test/**/*.csproj
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Package'
  inputs: 
    command: 'pack'
    packagesToPack: "src/**/*.csproj"
    arguments: '--no-restore --no-build'
    packDestination: '$(Build.ArtifactStagingDirectory)/'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'

- task: DotNetCoreCLI@2
  displayName: 'Push'
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.Tests.nupkg'
    feedPublish: 'Clearly .NET/Clearly'
    nuGetFeedType: 'internal'
    

